image: ruby:2.5

variables:
  JEKYLL_ENV: production

pages:
  script:
  - cd docs
  - gem update --system
  - gem install bundler
  - bundler update --bundler
  - bundle install
  
  - bundle exec jekyll build
  artifacts:
    paths:
    - public
  only:
  - master
