title: Codewind
email: codewind-dev@eclipse.org
description: Eclipse Codewind
keywords: Eclipse, docker, container, devops, applications, development, iteration, microservices, cloud, services, rapid, integrated
baseurl: "/codewind"

# Build settings
markdown: kramdown
kramdown:
  auto_ids          : true
  toc_levels        : [1, 2, 3, 4, 5, 6]
  input             : GFM
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
exclude: [node_modules]
collections:
  documentations:
    output: true
  news:
    output: true
  newsarchive:
    output: true